### ISSUE TITLE
top nav doesn't change

### ISSUE THREAD

**Issue by ZiiX** [csalmeida/protonmail-themes#1]
First, thank you for making these & your time.

You've may have noticed but the top nav bar no longer changes to black with the recent updates — it stays the default color. Can this still be overridden? 

Thanks again!

**Comment by csalmeida** [comment]
@ZiiX I've had a couple messages coming my way about this issue. It looks like [ProtonMail](https://protonmail.com/) released a few updates. I will update all themes as soon as I have a spare minute.

Meanwhile please have a look at [ProtonMail's Official Theme](http://protonmail.tumblr.com/) blog as they might include the most up-to-date themes.

Thank you for letting me know, I will fix this soon.

**Comment by VVSidorov** [comment]
It looks like the header id was changed from "pm_header-desktop" to "pm_headerDesktop". Simply replace "#pm_header-desktop" with "#pm_headerDesktop" in the CSS and it should solve the issue. (Note that you need to replace all occurrences.) Haven't thoroughly tested it, but it seemed to work with the blue and orange theme on desktop.

I haven't looked into mobile, but I would assume they also changed the id's there.

**Comment by csalmeida** [comment]
@ZiiX @VVSidorov 
I have updated the [themes to the latest version](https://github.com/csalmeida/protonmail-themes/tree/master/Themes/v3.7.3) and added a [SCSS template ](https://github.com/csalmeida/protonmail-themes/blob/master/Themes/v3.7.3/theme_template/template_v3.7.3.scss)if you want to create your own or have a look at this [theme creator](http://www.csalmeida.com/demos/quark/).

It's very likely that ProtonMail will change more aspects of its front-end soon, so please let let me know of any other issues you find.

Appreciate the feedback.
