### ISSUE TITLE
[Question] Is it not possible to make the massive white area a different color?

### ISSUE THREAD

**Issue by pullup** [csalmeida/protonmail-themes#16]
These themes kind of seem useless without addressing the main issue.
Is it not possible to change the bulk of the window?

![this part](https://lewd.pics/p/Btax.png)

**Comment by csalmeida** [comment]
The settings background can be changed by adding the color you would like to the settings `class`.

A short example of what it would look like on `_styles.scss`:
```
.settings {
   background: $base;
}
```
> Keep in mind this might lead you to change other elements in order for the text to be clearly visible.

I would like to add a dark theme soon but unfortunately I cannot find the time at the moment, but I hope that helps with your question.

**Comment by csalmeida** [comment]
Closed due to inactivity.
