### ISSUE TITLE
CSS Proton Mail

### ISSUE THREAD

**Issue by esysfound** [csalmeida/protonmail-themes#30]
Hi-just a copy of what I wrote on Reddit - but the ProtonMail CSS you've developed is great.

Best would be a short menu that just labelled some key variables e.g. Top Banner, Side Verticle Banner Menu Fonts etc..  You could set each variable as a "theme", and then refer to it throughout the CSS.  That way all the user has to do is put in whatever color they want in each variable, and it then propagates.  That is what I have done in effect - but more by just seeing how you used certain colors, and  searching and replacing all refs. to that color (all obviously in hex code).  It is a crude way to do it, but it works.

Sorry best I can do as I have a job and family that require focus.  Thanks for the help.

Maybe some dark grey shade with white text in the active writing pane (or at least a way to clearly change it) vs. white. Again if you just labelled clearly what some theme color choices are in a header section, for different elements - the user can then just tweak the hex code easily. Have done this with other CSS sheets. So at the top, the user just makes a few simple choices, and then as all the CSS instructions are relative, it would propagate easily.

**Comment by csalmeida** [comment]
@esysfound, thanks for creating an issue, I would appreciate if you could edit the title as well as the description to be more clear as in what you mean. Do you mean having a set of `CSS` variables at the top of the file that can be edited set theme colors?

Or perhaps is this is a theme suggestions would appreciate if you provided a color palette with at least four values and we can look into adding it in.

- Reference to the Reddit post where this was suggested: https://www.reddit.com/r/ProtonMail/comments/dzy836/experiments_with_dark_mode_on_v4/

**Comment by csalmeida** [comment]
Thanks for updating the issue. At the moment a whole theme colour scheme can be set at the top of it's `.scss` file by setting four core variables:

```scss
$base: #1C1C1C;
$search: #000;
$highlight: #2FBF71;
$navigation: #fff;
```

The will propagate through the whole theme when a `.css` file is built with `npm run build`.

However, if you mean that the variables should be set at the top of a `.css` file and propagate to all elements this could be possible but the benefits of `SCSS` functions would have to be removed. 

These allow to extend the use of a colour and change tones when themes are compiled, it reduced the amount of variables that need setting for a theme to be put together and let's `SCSS` do the heavy lifting in placing those across the styles. An example would be

For that reason I either suggest you clone the project and [follow the setup guide](https://github.com/csalmeida/protonmail-themes/tree/themes-v4#quick-setup-guide) to change the variables and generate a theme with your palette of choice. Please feel free to ask any questions if you do get stuck. :)

```scss
lighten($base, 5%)
```

Alternatively, you might have to change the values on the `.css` file on every instance has you've been doing so far.

Please let me know if this helps.

**Comment by esysfound** [comment]
Thanks will test when I have time - a bit hectic now.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by csalmeida** [comment]
Closed due to inactivity.
