### ISSUE TITLE
Unread emails are white in Row layout (v4)

### ISSUE THREAD

**Issue by laurens94** [csalmeida/protonmail-themes#31]
I'm not sure if you already want issues for the v4 versions, but I'll post this anyway ;)

Everything looks perfect in Column layout (the email preview-pane), but in Row layout the unread emails seem to have a white background.

Keep up the good work! It's much appreciated 👍

**Comment by csalmeida** [comment]
Absolutely, thanks for reporting this @laurens94. Could you let me know which theme you are using? I cannot replicate this in any of them at the moment.

I assume it is the full version of a theme, if so could you give this a try and let me know if you still have the issue?
https://raw.githubusercontent.com/csalmeida/protonmail-themes/themes-v4/themes/green_lume/green_lume_full.css

All themes can be found here for `v4.0.0`:
https://github.com/csalmeida/protonmail-themes/tree/themes-v4/themes

**Comment by laurens94** [comment]
I was using exactly that theme! ;)

It seems the following css (from the default Protonmail styling) is making it white:

```
.conversation:not(.read):not(.active) {
  background: #fff;
}
```

This piece of css (from the Green Lume full theme) makes it gray, but only in Column layout:

```
.conversation.item-container:not(.item-contact):not(.read):not(.active) {
  background: #292929;
}
```

The class for the row-layout is: `item-container-row`, that's why `.conversation.item-container` doesn't do anything here. This should do the trick:

```
.conversation.item-container:not(.item-contact):not(.read):not(.active),
.conversation.item-container-row:not(.item-contact):not(.read):not(.active) {
  background: #292929;
}
```

**Comment by csalmeida** [comment]
That's great! However, has the stylesheet I've linked previously worked as expected? I believe I've experienced this whilst building the theme. 😄

**Comment by laurens94** [comment]
Not sure, this is the first time I'm using v4 themes. I guess protonmail has changed the class `item-container` in the row layout or something. 

Btw, I believe they added a new navigation pane in settings (e.g. on https://beta.protonmail.com/settings/appearance) which is also white in the dark theme 😉

**Comment by csalmeida** [comment]
I meant if you can paste the theme below on the appearance pane and let know if you still experience the issue please: https://raw.githubusercontent.com/csalmeida/protonmail-themes/themes-v4/themes/green_lume/green_lume_full.css 👍

**Comment by laurens94** [comment]
Nope, didn't solve it.. But I added a Pull Request with the fixes (and a few other changes) 😁 

https://github.com/csalmeida/protonmail-themes/pull/32

**Comment by csalmeida** [comment]
Sorry to hear that! Could you send a screenshot of which element is affected exactly? I found that `.subnav` did have a white background but I assume the issue you are experiencing are with the message items themselves?

<img width="373" alt="Screenshot 2019-12-04 at 15 31 37" src="https://user-images.githubusercontent.com/12223613/70156060-3d300f80-16ab-11ea-8cdc-05639410c7e0.png">

> Seen on the Appearance Tab 

Thank you for the pull request @laurens94! I've added a few notes. 👍

**Comment by laurens94** [comment]
Where can I find these notes?

Here's the element, it's the message items indeed: 

![afbeelding](https://user-images.githubusercontent.com/5780704/70158833-35c33300-16b8-11ea-89f7-b08323916f1b.png)

You need to make sure you switch to Row layout to see it:

![afbeelding](https://user-images.githubusercontent.com/5780704/70158882-48d60300-16b8-11ea-838d-404601362c75.png)

In the Row layout there's also a white background when you have less than a screen-filling amount of emails:

![afbeelding](https://user-images.githubusercontent.com/5780704/70159030-86d32700-16b8-11ea-81dc-359d65381f36.png)

**Comment by csalmeida** [comment]
I can replicate it now, thank you. 🙇🏻‍♂️ I've left notes on the pull request you've raised #32.
