### ISSUE TITLE
Inbox by Gmail

### ISSUE THREAD

**Issue by Madis0** [csalmeida/protonmail-themes#42]
Could you do a v4 theme that looks like the deprecated [Inbox by Gmail](https://www.extremetech.com/wp-content/uploads/2014/10/google-inbox-unsnoozed-bundles-main-view-e1414086431916.jpg)?

You can see [one made for the older Protonmail version](https://scastiel.gitlab.io/protonmail-theme-creator/) here.

**Comment by csalmeida** [comment]
Absolutely, I have [added a theme](https://github.com/csalmeida/protonmail-themes/blob/inbox-theme/themes/inbox/inbox.css) with the Inbox theme colours.

**Comment by Madis0** [comment]
Could you make the left sidebar (mail, contacts, calendar) and mail header (mark read/unread, trash, archive, ...) white? That would look like the [drawer menu](https://images.techhive.com/images/article/2014/10/inbox-google-promos-100526386-large.idge.jpg) and [mail header](https://cdn.arstechnica.net/wp-content/uploads/2019/04/RIP-Inbox_0000_chrome_2019-04-01_11-51-43.png).

**Comment by csalmeida** [comment]
I've changed the sidebar, I'll add it to the roster of themes for now and I'll accept changes and tweaks to it overtime. You can [access the latest version of the theme](https://github.com/csalmeida/protonmail-themes/blob/themes-v4/themes/inbox/inbox.css) on `themes-v4`.

Thanks for the suggestion.
