### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oxr463** [csalmeida/protonmail-themes#44]
See: https://choosealicense.com/no-permission

**Comment by csalmeida** [comment]
@oxr463 thank you for pointing this out. I will have a look whenever possible. In the meantime could you expand on your thoughts on licensing and do you have any suggestions on what might be best for this project?

It seems either an [MIT License](https://choosealicense.com/licenses/mit/) or [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) would be appropriate.

**Comment by oxr463** [comment]
Personally, I would choose the GPL-3.0-or-later, so that any sub-themes are also free software.

**Comment by csalmeida** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a license to the project](https://trello.com/c/c3I85Mv3/8-add-a-license-to-the-project)

**Comment by csalmeida** [comment]
A license was added to the project, closing.
