### ISSUE TITLE
Gray-on-Gray in Plain Text Composition Box, Light-Gray-on-White in Address Fields

### ISSUE THREAD

**Issue by seascape** [csalmeida/protonmail-themes#46]
This is ProtonMail 4.0.0-beta7 with custom theme Green Lume:

![ProtonMail](https://user-images.githubusercontent.com/1672115/78085346-89e0da00-736f-11ea-8195-ad66dfed8938.png)

When I got the theme last week I recall there being light and "full" / dark versions. (Did you remove / consolidate them?) Anyway, I tested the full/dark versions of both Green Lume and Vitamin C with the above result in the plain text composition box and in the address fields.

It's possible there are other buggy bits but this is all I've noticed so far. I use the Firefox add-on Dark Background and Light Text atop the theme(s) to brute-force said areas back into normal readability.

**Comment by csalmeida** [comment]
Thank you for opening an issue with more context @seascape.

I can replicate the issue and found a few other elements to fix along the way (#47), according to the screenshot it could be you're using an outdated version of the theme.

If that's the case, please give the following a try:

- [Green Lume](https://raw.githubusercontent.com/csalmeida/protonmail-themes/themes-v4/themes/green_lume/green_lume_full.css)
- [Vitamin C](https://raw.githubusercontent.com/csalmeida/protonmail-themes/themes-v4/themes/vitamin_c/vitamin_c_full.css)

You should see the following:

![Screenshot 2020-04-01 at 20 49 11](https://user-images.githubusercontent.com/12223613/78180551-dc4af500-745a-11ea-8071-93f9bed1741d.png)
> Green Lume `4.0.0-beta12`

![Screenshot 2020-04-01 at 20 48 18](https://user-images.githubusercontent.com/12223613/78181254-f507da80-745b-11ea-8d82-abc9ca790a45.png)
> Vitamin C `4.0.0-beta12`

Let me know if that helps.

**Comment by seascape** [comment]
Hey again. I appreciate you looking into this. 

However, as I noted above, when I downloaded the theme(s) from this repository in March, I believe I chose version(s) with dark backgrounds in the composition boxes. It seems you only have white backgrounds now? Did that change or am I going crazy?

**Comment by csalmeida** [comment]
You are correct (and definitely not going crazy). I initially intended to add dark backgrounds to the composition boxes and the received email panel but haven't found a way to keep it from breaking when newsletters and other emails would inevitably include inline styles in the markup. For that reason the change has been rolled back for now.

The Protonmail team has also chosen to steer away from that approach (not entirely sure if it was even attempted to be honest) when implementing the official dark mode. 

I'm always keen to see a PR if someone is interested in giving it a try too but for now there won't be a dark background on any of those panels to avoid breaking the experience for other users.

When and if I find time to revive [Quark](https://github.com/csalmeida/quark) I might add it as a feature for anyone that has that preference but can live with a broken newsletter here and there.

> PS: In case you've found that _all_ themes did not have a "dark" version you could be looking at the `master` branch, you can [find all themes for `v.4.0.x` on the `themes-v4` branch](https://github.com/csalmeida/protonmail-themes/tree/themes-v4/themes). 

Hope this helps somehow and I'm sorry that those panels are no longer dark. Let me know. 🙇🏻‍♂️

**Comment by seascape** [comment]
Oh, it's all good. I appreciate the explanation! And ah, yes, that link is where I found the dark-comp ones previously.

The reason I ended up looking for third-party themes again, actually, was disappointment with the official dark theme beta. When there's still a large portion of the screen in bright white it makes me wonder if they really know why people want dark themes, ha.

**Comment by csalmeida** [comment]
No worries, I know it does not change anything but at least you get to know why?

> When there's still a large portion of the screen in bright white it makes me wonder if they really know why people want dark themes, ha.

I understand where you're coming from and I agree. That's is why I went for the dark styled panels until realising it was more challenging than I initially thought.

I'm going to revisit this when I next work on the themes, there could be a way I've overlooked or there could be a solution where the text only emails can be in dark mode but html based ones will have the bright panel.

**Comment by csalmeida** [comment]
Merge #50 has changes to make the new message panel apply the `$base` color of a theme, this will result the full version of themes with a dark color such as Green Lume and Dark Bubble Gum to have a dark background when composing messages. It also fixes the low contrast between text and background in plain text emails.

I still believe it is not feasible to extend this to message content panels as it would make most emails unreadable.

![Screenshot 2020-06-04 at 19 46 03](https://user-images.githubusercontent.com/12223613/83800704-ce566200-a69f-11ea-9da4-c0436d70edc5.png)
