### ISSUE TITLE
Padlock colour

### ISSUE THREAD

**Issue by bhz0u** [csalmeida/protonmail-themes#51]
I'm wondering if the padlock colour can be adjusted depending on how the message is encrypted. 

In the default theme, PM's emails and internal emails from other users get the purple padlock, PGP encrypted messages from external providers used to get a green padlock but seems like it doesn't do that on v4 and unencrypted messages gets solid black. In the custom themes, all the messages get the same padlock colour. 
[See a few screen shots comparing the custom theme and default theme](https://photos.app.goo.gl/TyM4ZYeMQttfPG788)

**Comment by csalmeida** [comment]
Good catch @Ghost-Recon131 and thank you for providing a fair amount of detail as well as screenshots to the issue! I did not notice that the colour changed depending on the encryption status and I've now patched it at #52.

The regular version of the themes will use the highlight colour for the lock when encrypted end-to-end and a black one when stored with zero access encryption.

The _full_ version will still use the highlight colour for e2e encrypted emails but the colour for zero access encrypted stored emails will be white.

Please let me know if that helps.

**Comment by bhz0u** [comment]
Works perfectly thanks!
