### ISSUE TITLE
Light text doesn't display well when composing "plain text" emails

### ISSUE THREAD

**Issue by Jake-Gillberg** [csalmeida/protonmail-themes#55]
Noticed while using the v4 `gruvbox_full` theme.

I imagine this is also a problem for any other themes using light-colored text. The composition box is white and the text inside of it remains light.

**Comment by csalmeida** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Light text doesn't display well when composing "plain text" emails](https://trello.com/c/uy7xzR6j/12-light-text-doesnt-display-well-when-composing-plain-text-emails)

**Comment by csalmeida** [comment]
Thank you for letting me know! I've submitted a fix at #56, please [use this version of the theme](https://raw.githubusercontent.com/csalmeida/protonmail-themes/fixes/themes/gruvbox/gruvbox_full.css) if you would like to take a look.

Just to be sure, the plain text email compose box should be styled as follows:

![Screenshot 2020-09-16 at 13 00 15](https://user-images.githubusercontent.com/12223613/93335361-41827f00-f81e-11ea-871c-99d57a015a56.png)
> Regular theme


![Screenshot 2020-09-16 at 12 59 44](https://user-images.githubusercontent.com/12223613/93335412-53fcb880-f81e-11ea-837d-4067a691e221.png)
> Full theme

Let me know if this helps and fixes the issue. 😄

**Comment by Jake-Gillberg** [comment]
Wow, what a quick fix! This works great, thanks!
