### ISSUE TITLE
Unable to activate Dark Mode

### ISSUE THREAD

**Issue by wasobi** [csalmeida/protonmail-themes#61]
I have been looking around the code to see if I missed something about how to turn on dark mode but I came up short. The preview shows that a dark mode is available for some themes. In my case, the theme in question is Dracula. I believe there is a  class or something missing in the scss however, I am not too familiar with scss/css because I don't use it often. The case may be that I am overlooking something.

**Comment by csalmeida** [comment]
Hi @wasobi, you probably didn't miss anything in the code. Could it be that:

1. You're using an unsupported version of themes?

These themes support version `v.4.x.x` of ProtonMail which is still in Beta and you can access that version of the app here: https://beta.protonmail.com

You can also access the themes for `v3.15` as well but these do not support dark mode.

2. Have you missed the Dark Mode toggle button?

In the latest version of the Beta, ProtonMail now has a dark mode toggle button. Does the theme change when you click it?

<img width="283" alt="Screenshot 2021-01-07 at 23 45 33" src="https://user-images.githubusercontent.com/12223613/104593265-573a7080-5667-11eb-99c9-81eb7c3d7589.png">

Please let me know if this helps!

> This issue seems to be related with #60.

**Comment by wasobi** [comment]
Ha, I just signed up for Proton so I didn't know that you had to sign in using beta.protonmail.com to use v.4.x.x. Thank you so much for the tip!

**Comment by csalmeida** [comment]
No worries! A few users have found hard to find the dark mode button so thought there was a chance that could be the issue. Let me know if that works for you.

**Comment by wasobi** [comment]
Okay, everything is working now. I am so happy that this was resolved. I was becoming obsessed with finding a solution.
