### ISSUE TITLE
Nord Full theme and V4

### ISSUE THREAD

**Issue by Candlemass** [csalmeida/protonmail-themes#67]
Hello,

I absolutely love this theme but sadly it's no longer working with the ProtonMail V4 rollout.

Are there any plans to port it over for use with stylus to work with V4 or at least something very similar available?

Cheers.

**Comment by Candlemass** [comment]
???????????

**Comment by Candlemass** [comment]
Is this project abandoned?

**Comment by csalmeida** [comment]
Hey @Candlemass, the project is not abandoned, I would like to issue an update soon but have been too busy. PRs are welcome of course!

**Comment by Candlemass** [comment]
@csalmeida

Thanks for the reply.

Any timeline on when these will be updated to work with V4?

Cheers.

**Comment by csalmeida** [comment]
I'll try to get an update out this month but it will really depend on my workload. I like this project and am glad that you're using it and looking forward to get a fix but it will need to wait until I have a gap in my schedule.

**Comment by Candlemass** [comment]
Great.

I will continue to keep an eye on this over the next month.

Thanks.

**Comment by Candlemass** [comment]
Hi,

So a month later is there any update?

**Comment by csalmeida** [comment]
@Candlemass have a look at this branch (#68), it's still a WIP but this theme in particular should be fine.
https://github.com/csalmeida/protonmail-themes/tree/v4.0.8

**Comment by csalmeida** [comment]
Fixed in #68, closing.
